package com.example.ptv.util

object FunFacts {
	private val FACTS = listOf(
		"Honey never spoils.",
		"Octopuses have three hearts.",
		"Bananas are berries.",
		"Strawberries aren't berries.",
		"A group of flamingos is called a flamboyance.",
		"Sea otters hold hands while sleeping.",
		"Cows have best friends.",
		"Koalas have fingerprints.",
		"Sharks existed before trees.",
		"Some jellyfish can revert to earlier life stages.",
		"Snails can sleep for years.",
		"There are more stars than grains of sand on Earth.",
		"Cleopatra lived closer to the moon landing than to the pyramids' construction.",
		"Wombat poop is cube-shaped.",
		"Mantis shrimp can punch at bullet speed.",
		"A day on Venus is longer than its year.",
		"Certain bamboo can grow nearly a meter a day.",
		"Sloths can hold their breath up to 40 minutes.",
		"Butterflies taste with their feet.",
		"Koalas sleep up to 20 hours a day.",
		"Humans share about 50% of DNA with bananas.",
		"Jellyfish have existed for over 500 million years.",
		"A blue whale's heart is as big as a small car.",
		"Ravens can solve complex problems.",
		"Penguins often give pebbles as gifts.",
		"Cheetahs cannot roar like lions.",
		"Dolphins use unique whistles like names.",
		"Cats have over 20 muscles to control each ear.",
		"Owls can't move their eyes; they swivel their heads.",
		"Mercury's day is about 59 Earth days long.",
		"Polar bears have black skin under white fur.",
		"The Eiffel Tower grows slightly in summer.",
		"Venus rotates opposite most planets.",
		"Giraffes and humans both have seven neck vertebrae.",
		"A group of crows is called a murder.",
		"Frogs can absorb water through their skin.",
		"There are more trees on Earth than stars in the Milky Way.",
		"Lightning is hotter than the sun's surface.",
		"Pineapples can take up to two years to grow.",
		"Bees can recognize human faces.",
		"The longest recorded chicken flight is 13 seconds.",
		"An ostrich's eye is larger than its brain.",
		"The inventor of the Pringles can is buried in one.",
		"A shrimp's heart is in its head.",
		"Some turtles can breathe through their cloaca.",
		"Babies are born with more bones than adults.",
		"A blue whale's tongue can weigh as much as an elephant.",
		"The human tongue has tiny bumps called papillae.",
		"Peanuts are legumes, not true nuts.",
		"Sea cucumbers can eject their internal organs to deter predators.",
		"Kangaroos can't walk backwards.",
		"Honeybee waggle dances show food direction.",
		"A group of jellyfish is called a smack.",
		"Axolotls can regenerate limbs and organs.",
		"Bamboo is a grass, not a tree.",
		"The world's smallest mammal is the bumblebee bat.",
		"Some fish can change sex during life.",
		"The Sahara was once green with lakes.",
		"Woolly mammoths coexisted with early humans.",
		"The peregrine falcon is the fastest bird in a dive.",
		"Some seahorses form monogamous pairs.",
		"The smell of rain is called petrichor.",
		"Dolphins sleep with half their brain awake.",
		"Coast redwoods include the tallest trees.",
		"Fruit flies were among the first animals in space.",
		"Some plants can move quickly, like the sensitive plant.",
		"A group of frogs can be called an army.",
		"Whales evolved from land mammals.",
		"The moon drifts away from Earth about 3.8 cm/year.",
		"Goldfish have months-long memories.",
		"Ocean plankton produce most of Earth's oxygen.",
		"A cockroach can live weeks without its head.",
		"The Amazon once flowed the other way.",
		"Bats are the only mammals that truly fly.",
		"The human nose can remember thousands of scents.",
		"Tomatoes were once thought poisonous in Europe.",
		"Camels have three eyelids for sand protection.",
		"The Mariana Trench is Earth's deepest point.",
		"Bristlecone pines are among the oldest trees.",
		"Some ants farm fungi and herd aphids.",
		"Human fingerprints are unique across individuals.",
		"Elephants can detect distant rainstorms.",
		"The Great Wall isn't visible from the moon unaided.",
		"A group of whales is called a pod.",
		"The Sun makes up ~99.86% of the solar system's mass.",
		"The Pacific Ocean is bigger than all land combined.",
		"Ada Lovelace is considered the first computer programmer.",
		"The letter 'E' is the most common in English.",
		"A single human hair can support about 100 grams.",
		"The longest known cave system spans hundreds of kilometers.",
		"The shortest war in history lasted less than an hour.",
		"A group of pandas is called an embarrassment.",
		"Some dogs can learn more than 1000 words.",
		"A snail can have tens of thousands of teeth.",
		"Hummingbirds can fly backwards.",
		"Some species of penguin propose with a pebble."
	)

	fun randomFact(): String = "💡Quick Fact: ${FACTS.random()}"
}